# Generated by Django 3.1 on 2020-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showmodel',
            name='phone_No',
            field=models.IntegerField(blank=True, help_text='Contact phone number'),
        ),
    ]
