# Generated by Django 3.1 on 2020-08-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200827_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showmodel',
            old_name='Academic',
            new_name='academic',
        ),
    ]
